#file level variables
- name: file level variables
  hosts: localhost
  vars_files: 
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am leaning {{course}}, and my traine is {{trainer}}, and duration of course {{duration}}"