#variables which are prefered first among all
#1.Using command line arguments first it will preferred.
#2.task
#3.
- name: variables are prefered first
  hosts:  localhost
  vars_files:
  - variables.yaml
  vars:
    person: "ram from play"
    wishes: "morning from play"
  vars_prompt:
  - name: person
    prompt: please enter name of person
    private: false
  - name: wishes
    prompt: please enter wishes
    private: false
  tasks:
  - name: variables are prefered first in task
    #vars:
    #  person: "ram from task"
    #  wishes: "morning from task"
    ansible.builtin.debug:
      msg: "Hi {{person}}, Good {{wishes}}"