- name: loops
  hosts: localhost
  become: true
  tasks:
  - name: print package
    ansible.builtin.package:
      name: "{{item}}"
      state: present # item is a default keyword
    loops:
    - git
    - mysql
    - postfix
