- name: loops
  hosts: localhost
  become: true
  tasks:
  - name: creating advance loops
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'} #item
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'nginx', state: 'present'}